import type {
  AuditEntry,
  DashboardStats,
  InspectionRecord,
  NonConformanceReport,
  SeverityPolicy,
  Supplier,
  UserAccount,
  VaultDocument,
} from "./types";

/**
 * Reference "today" used for deterministic derived stats. The UI passes the
 * real date; tests pass a fixed one.
 */
export function addDays(iso: string, days: number): string {
  const d = new Date(iso + "T00:00:00Z");
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}

export const suppliers: Supplier[] = [
  {
    id: "SUP-001",
    name: "Precision Metalworks Sdn Bhd",
    code: "PMW",
    category: "Machining",
    riskTier: "Low",
    passRate: 97.4,
    openNcrs: 0,
    lastAuditDate: "2026-06-11",
    status: "Active",
    trend: "improving",
    contactName: "Faridah Rahman",
    contactEmail: "faridah@precisionmetalworks.my",
    phone: "+60 4-226 8810",
    location: "Penang, Malaysia",
    overallScore: 94.4,
    kpis: { quality: 96, delivery: 94, responsiveness: 92, documentation: 95, pricing: 93 },
    weights: { quality: 0.35, delivery: 0.25, responsiveness: 0.15, documentation: 0.1, pricing: 0.15 },
    approvedSince: "2019-03-14",
    onTimeDeliveryPct: 97.8,
    ppmDefects: 42,
  },
  {
    id: "SUP-002",
    name: "Apex Plastics Industries",
    code: "API",
    category: "Plastics",
    riskTier: "Medium",
    passRate: 91.8,
    openNcrs: 0,
    lastAuditDate: null,
    status: "Active",
    trend: "stable",
    contactName: "Priya Nair",
    contactEmail: "quality@apexplastics.in",
    phone: "+91 22-4012 7755",
    location: "Navi Mumbai, India",
    overallScore: 85.6,
    kpis: { quality: 88, delivery: 85, responsiveness: 82, documentation: 86, pricing: 84 },
    weights: { quality: 0.35, delivery: 0.25, responsiveness: 0.15, documentation: 0.1, pricing: 0.15 },
    approvedSince: "2023-05-02",
    onTimeDeliveryPct: 90.2,
    ppmDefects: 480,
  },
  {
    id: "SUP-003",
    name: "Golden Circuit Electronics",
    code: "GCE",
    category: "Electronics",
    riskTier: "Low",
    passRate: 96.1,
    openNcrs: 0,
    lastAuditDate: "2026-07-30",
    status: "Active",
    trend: "stable",
    contactName: "Melissa Tan",
    contactEmail: "qa@goldencircuit.com",
    phone: "+60 3-5122 3400",
    location: "Kuala Lumpur, Malaysia",
    overallScore: 91.7,
    kpis: { quality: 94, delivery: 91, responsiveness: 90, documentation: 92, pricing: 89 },
    weights: { quality: 0.35, delivery: 0.25, responsiveness: 0.15, documentation: 0.1, pricing: 0.15 },
    approvedSince: "2021-01-19",
    onTimeDeliveryPct: 94.6,
    ppmDefects: 130,
  },
  {
    id: "SUP-004",
    name: "Ironbridge Stampings",
    code: "IBS",
    category: "Machining",
    riskTier: "High",
    passRate: 82.6,
    openNcrs: 1,
    lastAuditDate: "2026-02-19",
    status: "Active",
    trend: "declining",
    contactName: "Dale Kowalski",
    contactEmail: "sqe@ironbridge.com",
    phone: "+1 419-555-0147",
    location: "Toledo, OH",
    overallScore: 71.3,
    kpis: { quality: 74, delivery: 68, responsiveness: 66, documentation: 77, pricing: 72 },
    weights: { quality: 0.35, delivery: 0.25, responsiveness: 0.15, documentation: 0.1, pricing: 0.15 },
    approvedSince: "2018-11-05",
    onTimeDeliveryPct: 81.2,
    ppmDefects: 1240,
  },
  {
    id: "SUP-005",
    name: "Vantage Electronics Mfg.",
    code: "VEM",
    category: "Electronics",
    riskTier: "Medium",
    passRate: 93.5,
    openNcrs: 0,
    lastAuditDate: "2025-11-06",
    status: "Active",
    trend: "improving",
    contactName: "Hector Salinas",
    contactEmail: "quality@vantageem.com",
    phone: "+52 33-3880 2210",
    location: "Guadalajara, Mexico",
    overallScore: 86.1,
    kpis: { quality: 90, delivery: 85, responsiveness: 83, documentation: 86, pricing: 82 },
    weights: { quality: 0.35, delivery: 0.25, responsiveness: 0.15, documentation: 0.1, pricing: 0.15 },
    approvedSince: "2022-04-22",
    onTimeDeliveryPct: 91.6,
    ppmDefects: 195,
  },
  {
    id: "SUP-006",
    name: "Summit Heat Treating Co.",
    code: "SHT",
    category: "Raw Material",
    riskTier: "Medium",
    passRate: 90.0,
    openNcrs: 1,
    lastAuditDate: "2026-04-23",
    status: "Active",
    trend: "stable",
    contactName: "Gordon Blake",
    contactEmail: "lab@summitheat.com",
    phone: "+1 330-555-0182",
    location: "Canton, OH",
    overallScore: 81.6,
    kpis: { quality: 85, delivery: 79, responsiveness: 78, documentation: 84, pricing: 80 },
    weights: { quality: 0.35, delivery: 0.25, responsiveness: 0.15, documentation: 0.1, pricing: 0.15 },
    approvedSince: "2020-09-30",
    onTimeDeliveryPct: 88.0,
    ppmDefects: 265,
  },
  {
    id: "SUP-007",
    name: "Northline Cable & Wire",
    code: "NCW",
    category: "Raw Material",
    riskTier: "Low",
    passRate: 95.2,
    openNcrs: 0,
    lastAuditDate: "2026-01-28",
    status: "Active",
    trend: "stable",
    contactName: "Anne Friesen",
    contactEmail: "qa@northlinecw.com",
    phone: "+1 204-555-0163",
    location: "Winnipeg, MB",
    overallScore: 89.8,
    kpis: { quality: 92, delivery: 89, responsiveness: 88, documentation: 91, pricing: 87 },
    weights: { quality: 0.35, delivery: 0.25, responsiveness: 0.15, documentation: 0.1, pricing: 0.15 },
    approvedSince: "2019-06-11",
    onTimeDeliveryPct: 94.3,
    ppmDefects: 120,
  },
  {
    id: "SUP-008",
    name: "Redstone Machining Works",
    code: "RMW",
    category: "Machining",
    riskTier: "Critical",
    passRate: 68.3,
    openNcrs: 1,
    lastAuditDate: "2026-03-05",
    status: "Active",
    trend: "declining",
    contactName: "Carl Yoder",
    contactEmail: "plant@redstonemw.com",
    phone: "+1 814-555-0126",
    location: "Erie, PA",
    overallScore: 58.2,
    kpis: { quality: 62, delivery: 54, responsiveness: 50, documentation: 68, pricing: 58 },
    weights: { quality: 0.35, delivery: 0.25, responsiveness: 0.15, documentation: 0.1, pricing: 0.15 },
    approvedSince: "2017-02-08",
    onTimeDeliveryPct: 68.5,
    ppmDefects: 3850,
  },
  {
    id: "SUP-009",
    name: "Lakeshore Gasket & Seal",
    code: "LGS",
    category: "Packaging",
    riskTier: "Medium",
    passRate: 92.7,
    openNcrs: 0,
    lastAuditDate: "2025-12-09",
    status: "Active",
    trend: "stable",
    contactName: "Dana Oosterhuis",
    contactEmail: "quality@lakeshoregs.com",
    phone: "+1 231-555-0174",
    location: "Muskegon, MI",
    overallScore: 83.4,
    kpis: { quality: 86, delivery: 84, responsiveness: 79, documentation: 83, pricing: 81 },
    weights: { quality: 0.35, delivery: 0.25, responsiveness: 0.15, documentation: 0.1, pricing: 0.15 },
    approvedSince: "2021-08-16",
    onTimeDeliveryPct: 90.7,
    ppmDefects: 340,
  },
  {
    id: "SUP-010",
    name: "Apex Surface Finishing",
    code: "ASF",
    category: "Machining",
    riskTier: "High",
    passRate: 76.9,
    openNcrs: 1,
    lastAuditDate: "2026-07-16",
    status: "Inactive",
    trend: "declining",
    contactName: "Marcus Reed",
    contactEmail: "ops@apexfinish.com",
    phone: "+1 937-555-0119",
    location: "Dayton, OH",
    overallScore: 69.3,
    kpis: { quality: 72, delivery: 70, responsiveness: 61, documentation: 71, pricing: 69 },
    weights: { quality: 0.35, delivery: 0.25, responsiveness: 0.15, documentation: 0.1, pricing: 0.15 },
    approvedSince: "2019-12-03",
    onTimeDeliveryPct: 76.9,
    ppmDefects: 1980,
  },
  {
    id: "SUP-011",
    name: "Quantum Springs Inc.",
    code: "QSI",
    category: "Machining",
    riskTier: "Low",
    passRate: 96.8,
    openNcrs: 0,
    lastAuditDate: "2026-05-14",
    status: "Active",
    trend: "stable",
    contactName: "Beth McAllister",
    contactEmail: "quality@quantumsprings.com",
    phone: "+1 423-555-0158",
    location: "Bristol, TN",
    overallScore: 92.3,
    kpis: { quality: 95, delivery: 91, responsiveness: 90, documentation: 93, pricing: 90 },
    weights: { quality: 0.35, delivery: 0.25, responsiveness: 0.15, documentation: 0.1, pricing: 0.15 },
    approvedSince: "2020-05-27",
    onTimeDeliveryPct: 96.2,
    ppmDefects: 65,
  },
  {
    id: "SUP-012",
    name: "Fairfield Rubber Products",
    code: "FRP",
    category: "Plastics",
    riskTier: "Medium",
    passRate: 88.4,
    openNcrs: 1,
    lastAuditDate: null,
    status: "Active",
    trend: "declining",
    contactName: "Owen Huang",
    contactEmail: "qa@fairfieldrp.com",
    phone: "+1 641-555-0137",
    location: "Fairfield, IA",
    overallScore: 80.5,
    kpis: { quality: 83, delivery: 81, responsiveness: 75, documentation: 82, pricing: 78 },
    weights: { quality: 0.35, delivery: 0.25, responsiveness: 0.15, documentation: 0.1, pricing: 0.15 },
    approvedSince: "2022-10-14",
    onTimeDeliveryPct: 86.8,
    ppmDefects: 520,
  },
  {
    id: "SUP-013",
    name: "Brightwater Valves Ltd.",
    code: "BVL",
    category: "Machining",
    riskTier: "High",
    passRate: 74.8,
    openNcrs: 1,
    lastAuditDate: "2026-08-03",
    status: "Inactive",
    trend: "declining",
    contactName: "Oliver Grant",
    contactEmail: "quality@brightwatervalves.co.uk",
    phone: "+44 114-555-0142",
    location: "Sheffield, UK",
    overallScore: 67.1,
    kpis: { quality: 71, delivery: 64, responsiveness: 60, documentation: 73, pricing: 66 },
    weights: { quality: 0.35, delivery: 0.25, responsiveness: 0.15, documentation: 0.1, pricing: 0.15 },
    approvedSince: "2021-03-09",
    onTimeDeliveryPct: 74.1,
    ppmDefects: 2210,
  },
  {
    id: "SUP-014",
    name: "Keystone Extrusions",
    code: "KEX",
    category: "Raw Material",
    riskTier: "Low",
    passRate: 94.3,
    openNcrs: 0,
    lastAuditDate: "2026-03-26",
    status: "Active",
    trend: "stable",
    contactName: "Sofia Deluca",
    contactEmail: "quality@keystoneex.com",
    phone: "+1 717-555-0191",
    location: "Harrisburg, PA",
    overallScore: 88.1,
    kpis: { quality: 91, delivery: 87, responsiveness: 85, documentation: 88, pricing: 86 },
    weights: { quality: 0.35, delivery: 0.25, responsiveness: 0.15, documentation: 0.1, pricing: 0.15 },
    approvedSince: "2020-01-23",
    onTimeDeliveryPct: 92.5,
    ppmDefects: 150,
  },
  {
    id: "SUP-015",
    name: "Delta Industrial Coatings",
    code: "DIC",
    category: "Raw Material",
    riskTier: "Medium",
    passRate: 86.2,
    openNcrs: 0,
    lastAuditDate: "2026-06-30",
    status: "Active",
    trend: "stable",
    contactName: "Ray Colton",
    contactEmail: "lab@deltacoatings.com",
    phone: "+1 615-555-0128",
    location: "Nashville, TN",
    overallScore: 79.3,
    kpis: { quality: 82, delivery: 78, responsiveness: 74, documentation: 81, pricing: 79 },
    weights: { quality: 0.35, delivery: 0.25, responsiveness: 0.15, documentation: 0.1, pricing: 0.15 },
    approvedSince: "2023-02-06",
    onTimeDeliveryPct: 85.4,
    ppmDefects: 610,
  },
];

export const inspections: InspectionRecord[] = [
  {
    id: "INS-2411",
    lotNumber: "LOT-2026-08121",
    partNumber: "TNX-4410-A",
    partName: "Gearbox Housing Casting",
    supplierId: "SUP-001",
    poNumber: "PO-88231",
    receivedDate: "2026-08-18",
    inspectedBy: "R. Okafor",
    sampleSize: 32,
    lotQuantity: 400,
    passCount: 32,
    failCount: 0,
    aqlLevel: "1.0",
    disposition: "Accepted",
    inspectorNotes: "Dimensional report within print tolerances. Porosity check clean per ASTM E505.",
  },
  {
    id: "INS-2410",
    lotNumber: "LOT-2026-08118",
    partNumber: "TNX-2205-C",
    partName: "M8 Flange Bolt Class 10.9",
    supplierId: "SUP-002",
    poNumber: "PO-88198",
    receivedDate: "2026-08-17",
    inspectedBy: "J. Whitfield",
    sampleSize: 50,
    lotQuantity: 25000,
    passCount: 49,
    failCount: 1,
    aqlLevel: "1.0",
    disposition: "Accepted",
    inspectorNotes: "One unit below minimum head height. Within AQL acceptance number of 2.",
  },
  {
    id: "INS-2409",
    lotNumber: "LOT-2026-08114",
    partNumber: "TNX-7788-B",
    partName: "Actuator Housing Cover",
    supplierId: "SUP-003",
    poNumber: "PO-88174",
    receivedDate: "2026-08-14",
    inspectedBy: "M. Delgado",
    sampleSize: 50,
    lotQuantity: 1200,
    passCount: 46,
    failCount: 4,
    aqlLevel: "1.5",
    disposition: "Return to Supplier",
    inspectorNotes: "Flash at parting line exceeds 0.15 mm limit on 4 samples. Exceeds AQL rejection number; lot returned.",
  },
  {
    id: "INS-2408",
    lotNumber: "LOT-2026-08110",
    partNumber: "TNX-3320-D",
    partName: "Bracket Stamping LH",
    supplierId: "SUP-004",
    poNumber: "PO-88152",
    receivedDate: "2026-08-12",
    inspectedBy: "R. Okafor",
    sampleSize: 50,
    lotQuantity: 2000,
    passCount: 43,
    failCount: 7,
    aqlLevel: "1.5",
    disposition: "Rejected",
    inspectorNotes: "Edge cracking on flange radius. NCR-2608 raised. Lot segregated in quarantine cage Q-3.",
  },
  {
    id: "INS-2407",
    lotNumber: "LOT-2026-08107",
    partNumber: "TNX-9910-E",
    partName: "Control Board Assembly Rev C",
    supplierId: "SUP-005",
    poNumber: "PO-88140",
    receivedDate: "2026-08-11",
    inspectedBy: "T. Nakamura",
    sampleSize: 20,
    lotQuantity: 250,
    passCount: 20,
    failCount: 0,
    aqlLevel: "0.65",
    disposition: "Accepted",
    inspectorNotes: "Functional test 100% pass. Solder joint inspection per IPC-A-610 Class 3.",
  },
  {
    id: "INS-2406",
    lotNumber: "LOT-2026-08103",
    partNumber: "TNX-5560-F",
    partName: "Shaft Blank 42CrMo4 QT",
    supplierId: "SUP-006",
    poNumber: "PO-88129",
    receivedDate: "2026-08-10",
    inspectedBy: "J. Whitfield",
    sampleSize: 8,
    lotQuantity: 600,
    passCount: 8,
    failCount: 0,
    aqlLevel: "1.0",
    disposition: "Accepted",
    inspectorNotes: "Hardness 288-302 HB within spec band. Certification traceable to heat lot H-4471.",
  },
  {
    id: "INS-2405",
    lotNumber: "LOT-2026-08099",
    partNumber: "TNX-1180-G",
    partName: "Harness Assembly 12-Way",
    supplierId: "SUP-007",
    poNumber: "PO-88115",
    receivedDate: "2026-08-08",
    inspectedBy: "M. Delgado",
    sampleSize: 20,
    lotQuantity: 500,
    passCount: 20,
    failCount: 0,
    aqlLevel: "1.0",
    disposition: "Accepted",
    inspectorNotes: "Continuity and hipot test complete. No crimp height deviations observed.",
  },
  {
    id: "INS-2404",
    lotNumber: "LOT-2026-08095",
    partNumber: "TNX-2044-H",
    partName: "Spindle Bearing Journal Pin",
    supplierId: "SUP-008",
    poNumber: "PO-88097",
    receivedDate: "2026-08-06",
    inspectedBy: "R. Okafor",
    sampleSize: 32,
    lotQuantity: 800,
    passCount: 27,
    failCount: 5,
    aqlLevel: "0.65",
    disposition: "Rejected",
    inspectorNotes: "Surface finish Ra 1.9 um vs. 0.8 um requirement. NCR-2605 raised; supplier notified same day.",
  },
  {
    id: "INS-2403",
    lotNumber: "LOT-2026-08091",
    partNumber: "TNX-6621-J",
    partName: "Compressor Cover Gasket",
    supplierId: "SUP-009",
    poNumber: "PO-88082",
    receivedDate: "2026-08-05",
    inspectedBy: "T. Nakamura",
    sampleSize: 50,
    lotQuantity: 3000,
    passCount: 48,
    failCount: 2,
    aqlLevel: "1.5",
    disposition: "Accepted",
    inspectorNotes: "Minor die marks outside sealing zone. Within AQL acceptance criteria.",
  },
  {
    id: "INS-2402",
    lotNumber: "LOT-2026-08087",
    partNumber: "TNX-8830-K",
    partName: "Anodized Trim Extrusion",
    supplierId: "SUP-010",
    poNumber: "PO-88071",
    receivedDate: "2026-08-04",
    inspectedBy: "J. Whitfield",
    sampleSize: 32,
    lotQuantity: 900,
    passCount: 29,
    failCount: 3,
    aqlLevel: "1.5",
    disposition: "Use As Is",
    inspectorNotes: "Coating thickness 9.2 um vs 10 um min on 3 samples. Deviation DEV-2614 approved by engineering.",
  },
  {
    id: "INS-2401",
    lotNumber: "LOT-2026-08082",
    partNumber: "TNX-3050-L",
    partName: "Valve Return Spring",
    supplierId: "SUP-011",
    poNumber: "PO-88058",
    receivedDate: "2026-08-03",
    inspectedBy: "M. Delgado",
    sampleSize: 32,
    lotQuantity: 10000,
    passCount: 32,
    failCount: 0,
    aqlLevel: "1.0",
    disposition: "Accepted",
    inspectorNotes: "Spring rate and free length verified. Load-deflection curve nominal.",
  },
  {
    id: "INS-2400",
    lotNumber: "LOT-2026-08078",
    partNumber: "TNX-4122-M",
    partName: "Diaphragm Seal NBR-70",
    supplierId: "SUP-012",
    poNumber: "PO-88044",
    receivedDate: "2026-08-01",
    inspectedBy: "R. Okafor",
    sampleSize: 50,
    lotQuantity: 4500,
    passCount: 47,
    failCount: 3,
    aqlLevel: "2.5",
    disposition: "Accepted",
    inspectorNotes: "Shore hardness 69-72A. Two units with minor gate vestige; functionally acceptable.",
  },
  {
    id: "INS-2399",
    lotNumber: "LOT-2026-08074",
    partNumber: "TNX-4412-B",
    partName: "Housing Boss Pin",
    supplierId: "SUP-001",
    poNumber: "PO-88037",
    receivedDate: "2026-07-30",
    inspectedBy: "M. Delgado",
    sampleSize: 32,
    lotQuantity: 500,
    passCount: 32,
    failCount: 0,
    aqlLevel: "1.0",
    disposition: "Accepted",
    inspectorNotes: "CMM layout nominal across all five characteristics. Cert of conformance attached.",
  },
  {
    id: "INS-2398",
    lotNumber: "LOT-2026-08071",
    partNumber: "TNX-2208-Q",
    partName: "Connector Body Glass-Filled",
    supplierId: "SUP-002",
    poNumber: "PO-88031",
    receivedDate: "2026-07-28",
    inspectedBy: "J. Whitfield",
    sampleSize: 50,
    lotQuantity: 4000,
    passCount: 49,
    failCount: 1,
    aqlLevel: "1.5",
    disposition: "Accepted",
    inspectorNotes: "Single short shot identified at cavity 4; within acceptance number.",
  },
  {
    id: "INS-2397",
    lotNumber: "LOT-2026-08069",
    partNumber: "TNX-9912-F",
    partName: "Sensor Board Rev B",
    supplierId: "SUP-003",
    poNumber: "PO-88026",
    receivedDate: "2026-07-27",
    inspectedBy: "T. Nakamura",
    sampleSize: 20,
    lotQuantity: 300,
    passCount: 20,
    failCount: 0,
    aqlLevel: "0.65",
    disposition: "Accepted",
    inspectorNotes: "AOI and functional fixture pass. Conformal coating thickness verified at 30 um.",
  },
  {
    id: "INS-2396",
    lotNumber: "LOT-2026-08065",
    partNumber: "TNX-8831-A",
    partName: "Heatsink Extrusion 6063-T5",
    supplierId: "SUP-014",
    poNumber: "PO-88019",
    receivedDate: "2026-07-24",
    inspectedBy: "R. Okafor",
    sampleSize: 32,
    lotQuantity: 700,
    passCount: 31,
    failCount: 1,
    aqlLevel: "1.5",
    disposition: "Accepted",
    inspectorNotes: "One length oversize by 2 mm; within AQL. Fin pitch gauge check nominal.",
  },
  {
    id: "INS-2395",
    lotNumber: "LOT-2026-08061",
    partNumber: "TNX-1182-C",
    partName: "Power Cord Assembly 2 m",
    supplierId: "SUP-007",
    poNumber: "PO-88012",
    receivedDate: "2026-07-22",
    inspectedBy: "M. Delgado",
    sampleSize: 20,
    lotQuantity: 800,
    passCount: 20,
    failCount: 0,
    aqlLevel: "1.0",
    disposition: "Accepted",
    inspectorNotes: "Ground continuity and strain-relief pull test pass on all samples.",
  },
  {
    id: "INS-2394",
    lotNumber: "LOT-2026-08058",
    partNumber: "TNX-5562-G",
    partName: "Gear Blank 4140 QT",
    supplierId: "SUP-006",
    poNumber: "PO-88008",
    receivedDate: "2026-07-21",
    inspectedBy: "J. Whitfield",
    sampleSize: 8,
    lotQuantity: 450,
    passCount: 8,
    failCount: 0,
    aqlLevel: "1.0",
    disposition: "Accepted",
    inspectorNotes: "Case depth 1.4 mm vs 1.2-1.8 mm band. Microstructure per SAE J1268 acceptable.",
  },
  {
    id: "INS-2393",
    lotNumber: "LOT-2026-08054",
    partNumber: "TNX-9915-H",
    partName: "LED Driver Board Rev D",
    supplierId: "SUP-005",
    poNumber: "PO-88003",
    receivedDate: "2026-07-20",
    inspectedBy: "T. Nakamura",
    sampleSize: 20,
    lotQuantity: 260,
    passCount: 19,
    failCount: 1,
    aqlLevel: "1.0",
    disposition: "Accepted",
    inspectorNotes: "One board failed in-circuit test on rail 2; reworked and re-passed per ICT log.",
  },
  {
    id: "INS-2392",
    lotNumber: "LOT-2026-08049",
    partNumber: "TNX-3310-J",
    partName: "Bracket Stamping RH",
    supplierId: "SUP-004",
    poNumber: "PO-87998",
    receivedDate: "2026-07-18",
    inspectedBy: "R. Okafor",
    sampleSize: 50,
    lotQuantity: 2000,
    passCount: 45,
    failCount: 5,
    aqlLevel: "1.5",
    disposition: "Rejected",
    inspectorNotes: "Repeat of flange edge cracking on bend radius (see NCR-2608 history). Lot rejected; tooling review demanded.",
  },
  {
    id: "INS-2391",
    lotNumber: "LOT-2026-08046",
    partNumber: "TNX-3051-K",
    partName: "Retainer Spring 302 SS",
    supplierId: "SUP-011",
    poNumber: "PO-87992",
    receivedDate: "2026-07-17",
    inspectedBy: "M. Delgado",
    sampleSize: 32,
    lotQuantity: 12000,
    passCount: 32,
    failCount: 0,
    aqlLevel: "1.0",
    disposition: "Accepted",
    inspectorNotes: "Load at 8 mm deflection within 24-27 N band across all samples.",
  },
  {
    id: "INS-2390",
    lotNumber: "LOT-2026-08043",
    partNumber: "TNX-6625-L",
    partName: "Foam Seal Strip 6 mm",
    supplierId: "SUP-009",
    poNumber: "PO-87987",
    receivedDate: "2026-07-16",
    inspectedBy: "T. Nakamura",
    sampleSize: 50,
    lotQuantity: 2500,
    passCount: 48,
    failCount: 2,
    aqlLevel: "2.5",
    disposition: "Accepted",
    inspectorNotes: "Adhesive liner delamination on two strips outside seal zone; accepted per criteria.",
  },
  {
    id: "INS-2389",
    lotNumber: "LOT-2026-08039",
    partNumber: "TNX-6418-M",
    partName: "Valve Body 3/4 in Brass",
    supplierId: "SUP-013",
    poNumber: "PO-87980",
    receivedDate: "2026-07-15",
    inspectedBy: "J. Whitfield",
    sampleSize: 20,
    lotQuantity: 400,
    passCount: 17,
    failCount: 3,
    aqlLevel: "1.0",
    disposition: "Rejected",
    inspectorNotes: "Seat machining chips present in three bodies; bubble test failures. Escalated to SQE.",
  },
  {
    id: "INS-2388",
    lotNumber: "LOT-2026-08034",
    partNumber: "TNX-8840-N",
    partName: "Painted Enclosure Panel",
    supplierId: "SUP-015",
    poNumber: "PO-87974",
    receivedDate: "2026-07-14",
    inspectedBy: "R. Okafor",
    sampleSize: 32,
    lotQuantity: 350,
    passCount: 31,
    failCount: 1,
    aqlLevel: "1.5",
    disposition: "Use As Is",
    inspectorNotes: "Minor orange peel on one panel face; released under deviation DEV-2609 for interior units.",
  },
  {
    id: "INS-2387",
    lotNumber: "LOT-2026-08028",
    partNumber: "TNX-9918-P",
    partName: "Power Supply Module 24 V",
    supplierId: "SUP-005",
    poNumber: "PO-87966",
    receivedDate: "2026-07-10",
    inspectedBy: "T. Nakamura",
    sampleSize: 20,
    lotQuantity: 220,
    passCount: 20,
    failCount: 0,
    aqlLevel: "1.0",
    disposition: "Accepted",
    inspectorNotes: "Burn-in sample pass; ripple within limit. Labels compliant per spec rev D.",
  },
];

function eightD(doneCount: number) {
  const steps = [
    { step: "D1", label: "Team Formed" },
    { step: "D2", label: "Problem Described" },
    { step: "D3", label: "Containment" },
    { step: "D4", label: "Root Cause" },
    { step: "D5", label: "Corrective Actions" },
    { step: "D6", label: "Implemented" },
    { step: "D7", label: "Prevent Recurrence" },
    { step: "D8", label: "Team Recognition" },
  ];
  return steps.map((s, i) => ({ ...s, done: i < doneCount }));
}

export const ncrs: NonConformanceReport[] = [
  {
    id: "NCR-2608",
    supplierId: "SUP-004",
    partNumber: "TNX-3320-D",
    lotNumber: "LOT-2026-08110",
    title: "Flange edge cracking on bracket stampings",
    defectDescription:
      "Incoming inspection found radial edge cracks along the flange bend radius on 7 of 50 sampled brackets (LOT-2026-08110). Cracks initiate at the trim edge and propagate into the form radius, consistent with excessive blanking burr and insufficient clearance.",
    priority: "Critical",
    status: "Investigating",
    raisedDate: "2026-08-12",
    raisedBy: "R. Okafor",
    assignedEngineer: "L. Brennan",
    containmentAction:
      "Lot of 2,000 pcs quarantined in cage Q-3. Line-side stock verified clear. Interim 100% visual inspection at goods-in until further notice.",
    containmentEvidence: ["Quarantine cage Q-3 photo.jpg", "Goods-in sort report 2026-08-13.pdf"],
    rootCause: "",
    rootCauseCategory: "",
    eightDTeam: ["L. Brennan (lead)", "R. Okafor", "D. Kowalski (IBS)", "Process Eng. TBD"],
    correctiveActions: [
      {
        id: "CA-1",
        action: "Blanking die clearance audit and re-shim",
        owner: "Ironbridge Tooling",
        dueDate: "2026-09-05",
        status: "Planned",
      },
    ],
    quantityAffected: 2000,
    costImpactUsd: 18500,
    eightDProgress: eightD(2),
    activityLog: [
      { date: "2026-08-12", actor: "R. Okafor", event: "NCR raised from incoming inspection INS-2408." },
      { date: "2026-08-12", actor: "System", event: "Supplier notified via QSR portal." },
      { date: "2026-08-13", actor: "L. Brennan", event: "D1 team formed; D2 problem statement approved." },
      { date: "2026-08-14", actor: "D. Kowalski", event: "Containment confirmed complete at supplier stock." },
    ],
  },
  {
    id: "NCR-2605",
    supplierId: "SUP-008",
    partNumber: "TNX-2044-H",
    lotNumber: "LOT-2026-08095",
    title: "Journal pin surface finish out of specification",
    defectDescription:
      "Ground spindle pins measured Ra 1.9 um against drawing requirement of 0.8 um max. Five of 32 sampled parts failed profilometry (LOT-2026-08095). Risk of premature bearing wear in service.",
    priority: "Critical",
    status: "Containment Done",
    raisedDate: "2026-08-06",
    raisedBy: "R. Okafor",
    assignedEngineer: "L. Brennan",
    containmentAction:
      "Lot rejected and returned. All Redstone-machined pin lots from June onward recalled from FG stores and re-inspected; two additional suspect lots identified and quarantined.",
    containmentEvidence: ["Profilometry traces batch 1.pdf", "Recall memo RMW-2026-08.pdf"],
    rootCause: "",
    rootCauseCategory: "",
    eightDTeam: ["L. Brennan (lead)", "R. Okafor", "C. Yoder (RMW)", "Bearing SME: K. Patel"],
    correctiveActions: [],
    quantityAffected: 800,
    costImpactUsd: 42300,
    eightDProgress: eightD(3),
    activityLog: [
      { date: "2026-08-06", actor: "R. Okafor", event: "NCR raised; lot rejected at goods-in." },
      { date: "2026-08-07", actor: "L. Brennan", event: "Containment sweep of FG stores initiated." },
      { date: "2026-08-09", actor: "L. Brennan", event: "Two additional lots quarantined; D3 signed off." },
    ],
  },
  {
    id: "NCR-2601",
    supplierId: "SUP-013",
    partNumber: "TNX-6415-N",
    title: "Valve seat leakage above acceptance rate",
    defectDescription:
      "Customer returns traced to seat leakage exceeding 0.5 mL/min bubble test limit. Investigation linked to inconsistent lapping compound removal before assembly.",
    priority: "Major",
    status: "Root Cause Identified",
    raisedDate: "2026-07-21",
    raisedBy: "T. Nakamura",
    assignedEngineer: "J. Whitfield",
    containmentAction:
      "All finished valves held; 100% bubble test re-screen completed on 1,400 units. 38 leakers scrapped.",
    containmentEvidence: ["Bubble test re-screen results.xlsx"],
    rootCause:
      "Work instruction omitted final rinse after lapping. Compound residue caused intermittent seating during thermal cycling.",
    rootCauseCategory: "Work Instruction Gap",
    eightDTeam: ["J. Whitfield (lead)", "T. Nakamura", "O. Grant (BVL)", "Assembly Supervisor"],
    correctiveActions: [
      {
        id: "CA-1",
        action: "Revise work instruction WI-6415 to add post-lap rinse step",
        owner: "O. Grant (BVL)",
        dueDate: "2026-08-15",
        status: "Done",
      },
      {
        id: "CA-2",
        action: "Add rinse verification photo to traveler",
        owner: "BVL Production",
        dueDate: "2026-08-22",
        status: "In Progress",
      },
      {
        id: "CA-3",
        action: "Layered process audit of lapping cell for 4 weeks",
        owner: "J. Whitfield",
        dueDate: "2026-09-12",
        status: "Planned",
      },
    ],
    quantityAffected: 1400,
    costImpactUsd: 26800,
    eightDProgress: eightD(4),
    activityLog: [
      { date: "2026-07-21", actor: "T. Nakamura", event: "NCR opened from warranty return analysis." },
      { date: "2026-07-24", actor: "O. Grant", event: "100% re-screen completed at BVL." },
      { date: "2026-08-04", actor: "J. Whitfield", event: "D4 root cause confirmed via thermal cycle replication." },
      { date: "2026-08-15", actor: "O. Grant", event: "WI revision CA-1 completed and distributed." },
    ],
  },
  {
    id: "NCR-2598",
    supplierId: "SUP-010",
    partNumber: "TNX-8830-K",
    title: "Anodic coating thickness below minimum",
    defectDescription:
      "Type II anodize measured 9.2 um average versus 10 um minimum on sampled trim extrusions. Corrosion resistance margin reduced for outdoor exposure variants.",
    priority: "Major",
    status: "Verified",
    raisedDate: "2026-07-08",
    raisedBy: "J. Whitfield",
    assignedEngineer: "M. Delgado",
    containmentAction:
      "Affected lot released under deviation DEV-2614 for interior-use assemblies only. Outdoor allocations redirected to alternate anodizer.",
    containmentEvidence: ["Deviation DEV-2614 signed.pdf", "Coating thickness log w27.xlsx"],
    rootCause:
      "Rack density increased without re-validating current density; low current density produced thin coatings on rack centers.",
    rootCauseCategory: "Process Out of Control",
    eightDTeam: ["M. Delgado (lead)", "J. Whitfield", "M. Reed (ASF)", "Surface Finish SME"],
    correctiveActions: [
      {
        id: "CA-1",
        action: "Requalify rack loading pattern with current-density mapping",
        owner: "ASF Process",
        dueDate: "2026-08-01",
        status: "Done",
      },
      {
        id: "CA-2",
        action: "Add thickness CJK chart per rack position",
        owner: "ASF Quality",
        dueDate: "2026-08-08",
        status: "Done",
      },
    ],
    verification: { by: "M. Delgado", date: "2026-08-14" },
    quantityAffected: 900,
    costImpactUsd: 7600,
    eightDProgress: eightD(6),
    activityLog: [
      { date: "2026-07-08", actor: "J. Whitfield", event: "NCR raised from goods-in coating survey." },
      { date: "2026-07-15", actor: "M. Reed", event: "D4 confirmed: rack density change without validation." },
      { date: "2026-08-01", actor: "M. Reed", event: "CA-1 requalification complete; data reviewed." },
      { date: "2026-08-14", actor: "M. Delgado", event: "Effectiveness verified over 3 consecutive lots." },
    ],
  },
  {
    id: "NCR-2594",
    supplierId: "SUP-003",
    partNumber: "TNX-7788-B",
    lotNumber: "LOT-2026-06052",
    title: "Molding flash at actuator cover parting line",
    defectDescription:
      "Recurring flash up to 0.3 mm at parting line across three consecutive lots. Flash interferes with cover seal engagement during customer assembly.",
    priority: "Major",
    status: "Closed",
    raisedDate: "2026-06-17",
    raisedBy: "M. Delgado",
    assignedEngineer: "M. Delgado",
    containmentAction: "Three lots sorted 100%; 210 pieces rejected and returned for credit.",
    containmentEvidence: ["Sort summary June 2026.xlsx"],
    rootCause:
      "Tooling clamp wear allowed mold breathing at shot pressure. Tool refurbished with new clamp rails and vent re-cut.",
    rootCauseCategory: "Tooling Wear",
    eightDTeam: ["M. Delgado (lead)", "Tooling Engineer", "Golden Circuit Molding"],
    correctiveActions: [
      {
        id: "CA-1",
        action: "Refurbish tool clamps and re-cut vents",
        owner: "Golden Circuit Toolroom",
        dueDate: "2026-07-10",
        status: "Done",
      },
      {
        id: "CA-2",
        action: "Add mold maintenance interval to PM schedule",
        owner: "GCE Maintenance",
        dueDate: "2026-07-20",
        status: "Done",
      },
    ],
    verification: { by: "M. Delgado", date: "2026-07-28" },
    closure: { by: "L. Brennan", date: "2026-08-04" },
    quantityAffected: 3600,
    costImpactUsd: 11200,
    eightDProgress: eightD(8),
    activityLog: [
      { date: "2026-06-17", actor: "M. Delgado", event: "NCR raised after third consecutive flashed lot." },
      { date: "2026-06-25", actor: "GCE Toolroom", event: "D4 confirmed via mold-trial instrumentation." },
      { date: "2026-07-10", actor: "GCE Toolroom", event: "Tool refurbishment complete." },
      { date: "2026-07-28", actor: "M. Delgado", event: "Verification across 4 lots: zero flash defects." },
      { date: "2026-08-04", actor: "L. Brennan", event: "NCR closed by Quality Manager." },
    ],
  },
  {
    id: "NCR-2611",
    supplierId: "SUP-006",
    partNumber: "TNX-5560-F",
    lotNumber: "LOT-2026-08103",
    title: "Missing material certification revision",
    defectDescription:
      "Mill certs supplied referenced superseded revision of AMS 2759/1 heat treat spec. Documentation only; product hardness verified compliant.",
    priority: "Minor",
    status: "Open",
    raisedDate: "2026-08-20",
    raisedBy: "J. Whitfield",
    assignedEngineer: "J. Whitfield",
    containmentAction:
      "Certs requested from supplier. Product placed on document hold pending corrected certification.",
    containmentEvidence: ["Document hold tag H-221.jpg"],
    rootCause: "",
    rootCauseCategory: "",
    eightDTeam: ["J. Whitfield (lead)"],
    correctiveActions: [],
    quantityAffected: 600,
    costImpactUsd: 0,
    eightDProgress: eightD(1),
    activityLog: [
      { date: "2026-08-20", actor: "J. Whitfield", event: "NCR raised; certification revision mismatch." },
      { date: "2026-08-20", actor: "System", event: "Supplier acknowledgment requested." },
    ],
  },
  {
    id: "NCR-2609",
    supplierId: "SUP-012",
    partNumber: "TNX-4122-M",
    lotNumber: "LOT-2026-08078",
    title: "Gate vestige on diaphragm seals",
    defectDescription:
      "Cosmetic gate vestige noted on 2 of 50 sampled diaphragm seals. Vestige located outside functional seal area; no leak path identified.",
    priority: "Observation",
    status: "Investigating",
    raisedDate: "2026-08-15",
    raisedBy: "T. Nakamura",
    assignedEngineer: "T. Nakamura",
    containmentAction: "None required; observation recorded for supplier process review at next visit.",
    containmentEvidence: [],
    rootCause: "",
    rootCauseCategory: "",
    eightDTeam: ["T. Nakamura (lead)", "O. Huang (FRP)"],
    correctiveActions: [],
    quantityAffected: 0,
    costImpactUsd: 0,
    eightDProgress: eightD(1),
    activityLog: [
      { date: "2026-08-15", actor: "T. Nakamura", event: "Observation logged at goods-in sampling." },
    ],
  },
  {
    id: "NCR-2603",
    supplierId: "SUP-005",
    partNumber: "TNX-9910-E",
    lotNumber: "LOT-2026-06188",
    title: "Reflow tombstone on control boards",
    defectDescription:
      "Two of 250 boards failed AOI with tombstoned 0402 resistors on power rail. Boards failed functional test and were repaired under IPC-A-610.",
    priority: "Minor",
    status: "Closed",
    raisedDate: "2026-06-30",
    raisedBy: "T. Nakamura",
    assignedEngineer: "T. Nakamura",
    containmentAction: "Failed units repaired and re-tested. AOI escape review performed on prior two lots.",
    containmentEvidence: ["AOI escape review 2026-07-02.docx"],
    rootCause:
      "Uneven pad solder paste volume due to worn stencil apertures. Stencil replaced and aperture design updated.",
    rootCauseCategory: "Tooling Wear",
    eightDTeam: ["T. Nakamura (lead)", "H. Salinas (VEM)"],
    correctiveActions: [
      {
        id: "CA-1",
        action: "Replace stencil and revise aperture geometry",
        owner: "VEM Process",
        dueDate: "2026-07-18",
        status: "Done",
      },
    ],
    verification: { by: "T. Nakamura", date: "2026-07-25" },
    closure: { by: "L. Brennan", date: "2026-07-31" },
    quantityAffected: 250,
    costImpactUsd: 1800,
    eightDProgress: eightD(8),
    activityLog: [
      { date: "2026-06-30", actor: "T. Nakamura", event: "NCR raised from AOI yield monitoring." },
      { date: "2026-07-03", actor: "H. Salinas", event: "Stencil wear confirmed via volume inspection." },
      { date: "2026-07-18", actor: "VEM Process", event: "New stencil released to production." },
      { date: "2026-07-31", actor: "L. Brennan", event: "NCR closed." },
    ],
  },
];

const doc = (
  id: string,
  name: string,
  docType: VaultDocument["docType"],
  supplierId: string,
  version: string,
  uploadedDate: string,
  uploadedBy: string,
  approvalStatus: VaultDocument["approvalStatus"],
  fileType: VaultDocument["fileType"] = "pdf",
  sizeKb = 500,
): VaultDocument => ({
  id,
  name,
  docType,
  supplierId,
  version,
  uploadedDate,
  uploadedBy,
  approvalStatus,
  fileType,
  sizeKb,
});

export const documents: VaultDocument[] = [
  doc("DOC-101", "PPAP Level 3 Submission - TNX-3320-D Bracket.pdf", "PPAP", "SUP-004", "Rev C", "2026-08-14", "Ironbridge Stampings", "Pending"),
  doc("DOC-102", "Control Plan - Actuator Housing Cover.xlsx", "PPAP", "SUP-003", "v4.2", "2026-08-09", "Golden Circuit Electronics", "Approved", "xlsx", 310),
  doc("DOC-103", "PFMEA - Spindle Journal Pin Machining.pdf", "PPAP", "SUP-008", "v2.0", "2026-08-05", "Redstone Machining Works", "Pending"),
  doc("DOC-104", "IMDS Entry Confirmation - Trim Extrusion.pdf", "Certificate", "SUP-014", "Rev B", "2026-07-28", "Keystone Extrusions", "Approved"),
  doc("DOC-105", "Calibration Certificates Bundle Q3.xlsx", "Certificate", "SUP-006", "v1.1", "2026-07-25", "Summit Heat Treating Co.", "Approved", "xlsx", 720),
  doc("DOC-106", "ISO 9001:2015 Certificate - Precision Metalworks.pdf", "Certificate", "SUP-001", "2026 Issue", "2026-07-19", "Precision Metalworks Sdn Bhd", "Approved"),
  doc("DOC-107", "Deviation Request DEV-2614 - Anodize Thickness.docx", "SOP", "SUP-010", "v1.0", "2026-08-04", "Quality Engineering", "Approved", "docx", 145),
  doc("DOC-108", "Annual Capacity Survey - Vantage EM.docx", "PPAP", "SUP-005", "v3.0", "2026-07-11", "Vantage Electronics Mfg.", "Pending", "docx", 260),
  doc("DOC-109", "IATF 16949 Certificate - Northline Cable.pdf", "Certificate", "SUP-007", "2025 Issue", "2026-06-30", "Northline Cable & Wire", "Approved"),
  doc("DOC-110", "ISO 14001 Certificate - Apex Plastics.pdf", "Certificate", "SUP-002", "2025 Issue", "2026-06-24", "Apex Plastics Industries", "Pending"),
  doc("DOC-111", "PPAP Level 1 - TNX-3050-L Spring.xlsx", "PPAP", "SUP-011", "Rev A", "2026-06-18", "Quantum Springs Inc.", "Approved", "xlsx", 190),
  doc("DOC-112", "Audit Report AUD-2628 - Golden Circuit.pdf", "Audit Report", "SUP-003", "Final", "2026-08-06", "Quality Engineering", "Approved"),
  doc("DOC-113", "Audit Report AUD-2626 - Apex Surface Finishing.pdf", "Audit Report", "SUP-010", "Draft 2", "2026-07-28", "R. Okafor", "Pending"),
  doc("DOC-114", "Receiving Inspection Work Instruction WI-100.docx", "SOP", "SUP-001", "v3.1", "2026-06-12", "acme Quality", "Approved", "docx", 210),
  doc("DOC-115", "Supplier Corrective Action (SCAR) Procedure QP-8.7.docx", "SOP", "SUP-001", "v2.4", "2026-05-20", "acme Quality", "Approved", "docx", 180),
  doc("DOC-116", "Packaging Spec PKG-7741 ESD Trays.pdf", "SOP", "SUP-009", "v1.3", "2026-06-02", "Packaging Engineering", "Approved"),
  doc("DOC-117", "Audit Report AUD-2619 - Redstone Machining.pdf", "Audit Report", "SUP-008", "Final", "2026-03-28", "L. Brennan", "Approved"),
  doc("DOC-118", "PPAP Interim Approval - TNX-6418-M Valve Body.pdf", "PPAP", "SUP-013", "Rev B", "2026-07-02", "Brightwater Valves Ltd.", "Rejected"),
  doc("DOC-119", "Material Data Sheet 42CrMo4 - Summit Heat.pdf", "Certificate", "SUP-006", "Rev F", "2026-04-15", "Summit Heat Treating Co.", "Approved"),
  doc("DOC-120", "Conflict Minerals Reporting Template - Delta CMRT.xlsx", "Certificate", "SUP-015", "2026", "2026-05-08", "Delta Industrial Coatings", "Rejected", "xlsx", 640),
];

export const audits: AuditEntry[] = [
  {
    id: "AUD-2631",
    type: "Process Audit",
    auditor: "R. Okafor",
    location: "Ironbridge Stampings — Toledo, OH",
    date: "2026-08-27",
    status: "Scheduled",
    supplierId: "SUP-004",
    scope: "Stamping cells 1–3, tooling maintenance, NCR-2608 corrective actions.",
    checklistRef: "IATF 16949 §8.5.1 / CQI-9 Rev.4",
    team: ["R. Okafor (lead)", "L. Brennan", "Dale Kowalski (guide)"],
    findingsCount: 0,
  },
  {
    id: "AUD-2632",
    type: "Product Audit",
    auditor: "M. Delgado",
    location: "acme Goods-In Lab — Bay 4",
    date: "2026-08-29",
    status: "In Progress",
    findingsCount: 0,
    scope: "Quarterly re-verification of goods-in sampling plans and gauge R&R.",
    checklistRef: "QP-9.1.2 Product Audit Checklist v3",
    team: ["M. Delgado (lead)", "T. Nakamura"],
  },
  {
    id: "AUD-2633",
    type: "System Audit",
    auditor: "L. Brennan",
    location: "Redstone Machining Works — Erie, PA",
    date: "2026-09-03",
    status: "Scheduled",
    supplierId: "SUP-008",
    scope: "Follow-up on AUD-2619 major findings; SPC deployment verification.",
    checklistRef: "QMS System Audit Checklist v7",
    team: ["L. Brennan (lead)", "J. Whitfield"],
    findingsCount: 0,
  },
  {
    id: "AUD-2630",
    type: "Surveillance Audit",
    auditor: "BSI (external)",
    location: "acme HQ — Building 1",
    date: "2026-09-15",
    status: "Scheduled",
    scope: "ISO 9001:2015 / IATF 16949:2016 certificate maintenance visit.",
    checklistRef: "BSI surveillance plan 2026",
    team: ["Quality Manager", "Document Control"],
    findingsCount: 0,
  },
  {
    id: "AUD-2628",
    type: "System Audit",
    auditor: "J. Whitfield",
    location: "Golden Circuit Electronics — Kuala Lumpur",
    date: "2026-07-30",
    status: "Completed",
    supplierId: "SUP-003",
    scope: "Full QMS system audit ahead of volume ramp for sensor boards.",
    checklistRef: "QMS System Audit Checklist v7",
    team: ["J. Whitfield (lead)", "Melissa Tan (guide)"],
    findingsSummary:
      "2 minor findings: calibration records gap (gauge G-114); outdated work instruction at molding cell.",
    findingsCount: 2,
    closureStatus: "Closed",
  },
  {
    id: "AUD-2626",
    type: "Process Audit",
    auditor: "R. Okafor",
    location: "Apex Surface Finishing — Dayton, OH",
    date: "2026-07-16",
    status: "Overdue",
    supplierId: "SUP-010",
    scope: "Anodizing line process controls following coating thickness escapes.",
    checklistRef: "CQI-12 Coating Systems Assessment",
    team: ["R. Okafor (lead)"],
    findingsSummary:
      "1 major finding (rack qualification lapse, see NCR-2598); 1 minor (chemical control log).",
    findingsCount: 2,
    closureStatus: "Open",
  },
  {
    id: "AUD-2619",
    type: "System Audit",
    auditor: "L. Brennan",
    location: "Redstone Machining Works — Erie, PA",
    date: "2026-03-05",
    status: "Completed",
    supplierId: "SUP-008",
    scope: "Triennial full-system audit of Redstone machining operations.",
    checklistRef: "QMS System Audit Checklist v6",
    team: ["L. Brennan (lead)", "R. Okafor", "Carl Yoder (guide)"],
    findingsSummary:
      "2 majors: SPC not applied to grinding cells; training matrix incomplete. 3 minors.",
    findingsCount: 5,
    closureStatus: "Closed",
  },
  {
    id: "AUD-2612",
    type: "Surveillance Audit",
    auditor: "BSI (external)",
    location: "acme HQ — Building 1",
    date: "2025-09-12",
    status: "Completed",
    scope: "Annual certificate surveillance visit.",
    checklistRef: "BSI surveillance plan 2025",
    findingsSummary: "No nonconformities. 2 opportunities for improvement noted.",
    findingsCount: 0,
    closureStatus: "Closed",
  },
];

/** Portal user directory rendered by /settings. */
export const portalUsers: UserAccount[] = [
  { id: "USR-01", name: "Dana Reyes", email: "d.reyes@acme.com", role: "Quality Manager", status: "Active", lastActive: "2026-08-24" },
  { id: "USR-02", name: "Liam Brennan", email: "l.brennan@acme.com", role: "Quality Engineer", status: "Active", lastActive: "2026-08-24" },
  { id: "USR-03", name: "Rosa Okafor", email: "r.okafor@acme.com", role: "Quality Engineer", status: "Active", lastActive: "2026-08-21" },
  { id: "USR-04", name: "Jun Nakamura", email: "j.nakamura@acme.com", role: "Quality Engineer", status: "Active", lastActive: "2026-08-23" },
  { id: "USR-05", name: "Melissa Tan", email: "qa@goldencircuit.com", role: "Supplier User", status: "Active", lastActive: "2026-08-20" },
  { id: "USR-06", name: "Carl Yoder", email: "plant@redstonemw.com", role: "Supplier User", status: "Suspended", lastActive: "2026-06-30" },
];

/** NCR severity definitions with escalation rules (/settings). */
export const severityPolicies: SeverityPolicy[] = [
  {
    priority: "Critical",
    definition: "Affects safety, regulatory compliance, or stops the customer line.",
    containmentDays: 1,
    closureDays: 20,
    escalateTo: "VP Operations + Supplier Executive",
  },
  {
    priority: "Major",
    definition: "Functional defect or repeated escape likely reaching the customer.",
    containmentDays: 3,
    closureDays: 30,
    escalateTo: "Quality Manager",
  },
  {
    priority: "Minor",
    definition: "Isolated, non-functional deviation fully contained at goods-in.",
    containmentDays: 5,
    closureDays: 45,
    escalateTo: "SQE Lead",
  },
  {
    priority: "Observation",
    definition: "Improvement opportunity with no product impact.",
    containmentDays: 10,
    closureDays: 60,
    escalateTo: "SQE Lead (review only)",
  },
];

/** ANSI/ASQ Z1.4 sampling plans offered in /settings (lot-size band → sample). */
export const aqlSamplingPlans = [
  { lotBand: "2 – 8", sampleSize: 2, accept: 0, reject: 1 },
  { lotBand: "9 – 15", sampleSize: 3, accept: 0, reject: 1 },
  { lotBand: "16 – 25", sampleSize: 5, accept: 0, reject: 1 },
  { lotBand: "26 – 50", sampleSize: 8, accept: 0, reject: 1 },
  { lotBand: "51 – 90", sampleSize: 13, accept: 1, reject: 2 },
  { lotBand: "91 – 150", sampleSize: 20, accept: 1, reject: 2 },
  { lotBand: "151 – 280", sampleSize: 32, accept: 2, reject: 3 },
  { lotBand: "281 – 500", sampleSize: 50, accept: 3, reject: 4 },
  { lotBand: "501 – 1200", sampleSize: 80, accept: 5, reject: 6 },
  { lotBand: "1201 – 3200", sampleSize: 125, accept: 7, reject: 8 },
];

/** Document retention defaults (/settings). Years from approval. */
export const retentionPolicies = [
  { docType: "PPAP", years: 15 },
  { docType: "Certificate", years: 5 },
  { docType: "Audit Report", years: 10 },
  { docType: "SOP", years: 7 },
] as const;

/** Derives the dashboard KPI block deterministically from the mock corpus. */
export function computeDashboardStats(todayIso: string): DashboardStats {
  const today = new Date(todayIso + "T00:00:00Z");
  const cutoff30 = new Date(today);
  cutoff30.setUTCDate(cutoff30.getUTCDate() - 30);
  const cutoff30Iso = cutoff30.toISOString().slice(0, 10);
  const horizon14 = new Date(today);
  horizon14.setUTCDate(horizon14.getUTCDate() + 14);
  const horizon14Iso = horizon14.toISOString().slice(0, 10);

  const recentInspections = inspections.filter((i) => i.receivedDate >= cutoff30Iso);
  const avgPassRate =
    recentInspections.length === 0
      ? 0
      : Math.round(
          (recentInspections.reduce(
            (acc, i) => acc + (i.passCount / Math.max(i.sampleSize, 1)) * 100,
            0,
          ) /
            recentInspections.length) *
            10,
        ) / 10;

  const activeNcrList = ncrs.filter((n) => n.status !== "Closed");

  return {
    totalSuppliers: suppliers.length,
    activeSuppliers: suppliers.filter((s) => s.status === "Active").length,
    inactiveSuppliers: suppliers.filter((s) => s.status === "Inactive").length,
    avgPassRate,
    activeNcrs: activeNcrList.length,
    majorNcrs: activeNcrList.filter((n) => n.priority === "Major").length,
    minorNcrs: activeNcrList.filter((n) => n.priority === "Minor").length,
    overdueCorrectiveActions: ncrs.reduce(
      (acc, n) =>
        acc +
        n.correctiveActions.filter(
          (ca) => ca.dueDate < todayIso && ca.status !== "Done",
        ).length,
      0,
    ),
    upcomingAudits: audits.filter(
      (a) =>
        (a.status === "Scheduled" || a.status === "In Progress") &&
        a.date >= todayIso &&
        a.date <= horizon14Iso,
    ).length,
  };
}

export const lastAuditDate = "2025-09-12";
export const nextSurveillanceAudit = "2026-09-15";

export function getSupplier(supplierId: string): Supplier | undefined {
  return suppliers.find((s) => s.id === supplierId);
}

export function getNcr(ncrId: string): NonConformanceReport | undefined {
  return ncrs.find((n) => n.id === ncrId);
}
