import type {
  AuditEntry,
  DashboardStats,
  InspectionRecord,
  NonConformanceReport,
  Supplier,
  VaultDocument,
} from "./types";

export const suppliers: Supplier[] = [
  {
    id: "SUP-001",
    name: "Meridian Precision Castings",
    code: "MPC",
    riskTier: "Low",
    partCategory: "Aluminum Castings",
    contactEmail: "quality@meridianpc.com",
    location: "Cleveland, OH",
    overallScore: 94.2,
    kpis: { quality: 96, delivery: 93, responsiveness: 92, documentation: 95 },
    weights: { quality: 0.4, delivery: 0.3, responsiveness: 0.15, documentation: 0.15 },
    approvedSince: "2019-03-14",
    onTimeDeliveryPct: 97.8,
    ppmDefects: 42,
  },
  {
    id: "SUP-002",
    name: "Halvorsen Fastener Group",
    code: "HFG",
    riskTier: "Low",
    partCategory: "Fasteners & Hardware",
    contactEmail: "qa@halvorsenfg.com",
    location: "Rockford, IL",
    overallScore: 91.7,
    kpis: { quality: 94, delivery: 90, responsiveness: 89, documentation: 92 },
    weights: { quality: 0.4, delivery: 0.3, responsiveness: 0.15, documentation: 0.15 },
    approvedSince: "2020-07-02",
    onTimeDeliveryPct: 95.1,
    ppmDefects: 88,
  },
  {
    id: "SUP-003",
    name: "Cascade Polymer Solutions",
    code: "CPS",
    riskTier: "Medium",
    partCategory: "Injection Molded Plastics",
    contactEmail: "quality@cascadepoly.com",
    location: "Tacoma, WA",
    overallScore: 84.5,
    kpis: { quality: 87, delivery: 82, responsiveness: 80, documentation: 86 },
    weights: { quality: 0.35, delivery: 0.3, responsiveness: 0.2, documentation: 0.15 },
    approvedSince: "2021-01-19",
    onTimeDeliveryPct: 89.4,
    ppmDefects: 310,
  },
  {
    id: "SUP-004",
    name: "Ironbridge Stampings",
    code: "IBS",
    riskTier: "High",
    partCategory: "Metal Stampings",
    contactEmail: "sqe@ironbridge.com",
    location: "Toledo, OH",
    overallScore: 71.3,
    kpis: { quality: 74, delivery: 68, responsiveness: 66, documentation: 77 },
    weights: { quality: 0.4, delivery: 0.3, responsiveness: 0.15, documentation: 0.15 },
    approvedSince: "2018-11-05",
    onTimeDeliveryPct: 81.2,
    ppmDefects: 1240,
  },
  {
    id: "SUP-005",
    name: "Vantage Electronics Mfg.",
    code: "VEM",
    riskTier: "Medium",
    partCategory: "PCB Assemblies",
    contactEmail: "quality@vantageem.com",
    location: "Guadalajara, MX",
    overallScore: 86.9,
    kpis: { quality: 90, delivery: 85, responsiveness: 83, documentation: 86 },
    weights: { quality: 0.45, delivery: 0.25, responsiveness: 0.15, documentation: 0.15 },
    approvedSince: "2022-04-22",
    onTimeDeliveryPct: 91.6,
    ppmDefects: 195,
  },
  {
    id: "SUP-006",
    name: "Summit Heat Treating Co.",
    code: "SHT",
    riskTier: "Medium",
    partCategory: "Heat Treatment Services",
    contactEmail: "lab@summitheat.com",
    location: "Canton, OH",
    overallScore: 82.1,
    kpis: { quality: 85, delivery: 79, responsiveness: 78, documentation: 84 },
    weights: { quality: 0.4, delivery: 0.25, responsiveness: 0.15, documentation: 0.2 },
    approvedSince: "2020-09-30",
    onTimeDeliveryPct: 88.0,
    ppmDefects: 265,
  },
  {
    id: "SUP-007",
    name: "Northline Cable & Wire",
    code: "NCW",
    riskTier: "Low",
    partCategory: "Wire Harnesses",
    contactEmail: "qa@northlinecw.com",
    location: "Winnipeg, MB",
    overallScore: 90.4,
    kpis: { quality: 92, delivery: 89, responsiveness: 88, documentation: 91 },
    weights: { quality: 0.4, delivery: 0.3, responsiveness: 0.15, documentation: 0.15 },
    approvedSince: "2019-06-11",
    onTimeDeliveryPct: 94.3,
    ppmDefects: 120,
  },
  {
    id: "SUP-008",
    name: "Redstone Machining Works",
    code: "RMW",
    riskTier: "Critical",
    partCategory: "Precision Machined Components",
    contactEmail: "plant@redstonemw.com",
    location: "Erie, PA",
    overallScore: 58.6,
    kpis: { quality: 62, delivery: 54, responsiveness: 50, documentation: 68 },
    weights: { quality: 0.4, delivery: 0.3, responsiveness: 0.15, documentation: 0.15 },
    approvedSince: "2017-02-08",
    onTimeDeliveryPct: 68.5,
    ppmDefects: 3850,
  },
  {
    id: "SUP-009",
    name: "Lakeshore Gasket & Seal",
    code: "LGS",
    riskTier: "Medium",
    partCategory: "Gaskets & Seals",
    contactEmail: "quality@lakeshoregs.com",
    location: "Muskegon, MI",
    overallScore: 83.8,
    kpis: { quality: 86, delivery: 84, responsiveness: 79, documentation: 83 },
    weights: { quality: 0.35, delivery: 0.3, responsiveness: 0.2, documentation: 0.15 },
    approvedSince: "2021-08-16",
    onTimeDeliveryPct: 90.7,
    ppmDefects: 340,
  },
  {
    id: "SUP-010",
    name: "Apex Surface Finishing",
    code: "ASF",
    riskTier: "High",
    partCategory: "Plating & Anodizing",
    contactEmail: "ops@apexfinish.com",
    location: "Dayton, OH",
    overallScore: 69.4,
    kpis: { quality: 72, delivery: 70, responsiveness: 61, documentation: 71 },
    weights: { quality: 0.4, delivery: 0.25, responsiveness: 0.2, documentation: 0.15 },
    approvedSince: "2019-12-03",
    onTimeDeliveryPct: 76.9,
    ppmDefects: 1980,
  },
  {
    id: "SUP-011",
    name: "Quantum Springs Inc.",
    code: "QSI",
    riskTier: "Low",
    partCategory: "Springs & Wire Forms",
    contactEmail: "quality@quantumsprings.com",
    location: "Bristol, TN",
    overallScore: 92.8,
    kpis: { quality: 95, delivery: 91, responsiveness: 90, documentation: 93 },
    weights: { quality: 0.4, delivery: 0.3, responsiveness: 0.15, documentation: 0.15 },
    approvedSince: "2020-05-27",
    onTimeDeliveryPct: 96.2,
    ppmDefects: 65,
  },
  {
    id: "SUP-012",
    name: "Fairfield Rubber Products",
    code: "FRP",
    riskTier: "Medium",
    partCategory: "Molded Rubber",
    contactEmail: "qa@fairfieldrp.com",
    location: "Fairfield, IA",
    overallScore: 80.9,
    kpis: { quality: 83, delivery: 81, responsiveness: 75, documentation: 82 },
    weights: { quality: 0.35, delivery: 0.3, responsiveness: 0.2, documentation: 0.15 },
    approvedSince: "2022-10-14",
    onTimeDeliveryPct: 86.8,
    ppmDefects: 520,
  },
  {
    id: "SUP-013",
    name: "Brightwater Valves Ltd.",
    code: "BVL",
    riskTier: "High",
    partCategory: "Fluid Handling Valves",
    contactEmail: "quality@brightwatervalves.com",
    location: "Sheffield, UK",
    overallScore: 67.2,
    kpis: { quality: 71, delivery: 64, responsiveness: 60, documentation: 73 },
    weights: { quality: 0.4, delivery: 0.3, responsiveness: 0.15, documentation: 0.15 },
    approvedSince: "2021-03-09",
    onTimeDeliveryPct: 74.1,
    ppmDefects: 2210,
  },
  {
    id: "SUP-014",
    name: "Keystone Extrusions",
    code: "KEX",
    riskTier: "Low",
    partCategory: "Aluminum Extrusions",
    contactEmail: "quality@keystoneex.com",
    location: "Harrisburg, PA",
    overallScore: 88.3,
    kpis: { quality: 91, delivery: 87, responsiveness: 85, documentation: 88 },
    weights: { quality: 0.4, delivery: 0.3, responsiveness: 0.15, documentation: 0.15 },
    approvedSince: "2020-01-23",
    onTimeDeliveryPct: 92.5,
    ppmDefects: 150,
  },
  {
    id: "SUP-015",
    name: "Delta Industrial Coatings",
    code: "DIC",
    riskTier: "Medium",
    partCategory: "Paint & Coatings",
    contactEmail: "lab@deltacoatings.com",
    location: "Nashville, TN",
    overallScore: 79.5,
    kpis: { quality: 82, delivery: 78, responsiveness: 74, documentation: 81 },
    weights: { quality: 0.4, delivery: 0.25, responsiveness: 0.2, documentation: 0.15 },
    approvedSince: "2023-02-06",
    onTimeDeliveryPct: 85.4,
    ppmDefects: 610,
  },
];

export const inspections: InspectionRecord[] = [
  {
    id: "INS-2411",
    lotNumber: "LOT-2026-08121",
    partNumber: "TNX-4410-A",
    partName: "Gearbox Housing Casting",
    supplierId: "SUP-001",
    poNumber: "PO-88231",
    receivedDate: "2026-08-18",
    inspectedBy: "R. Okafor",
    sampleSize: 32,
    lotQuantity: 400,
    passCount: 32,
    failCount: 0,
    aqlLevel: "1.0",
    disposition: "Accepted",
    inspectorNotes:
      "Dimensional report within print tolerances. Porosity check clean per ASTM E505.",
  },
  {
    id: "INS-2410",
    lotNumber: "LOT-2026-08118",
    partNumber: "TNX-2205-C",
    partName: "M8 Flange Bolt Class 10.9",
    supplierId: "SUP-002",
    poNumber: "PO-88198",
    receivedDate: "2026-08-17",
    inspectedBy: "J. Whitfield",
    sampleSize: 50,
    lotQuantity: 25000,
    passCount: 49,
    failCount: 1,
    aqlLevel: "1.0",
    disposition: "Accepted",
    inspectorNotes:
      "One unit below minimum head height. Within AQL acceptance number of 2.",
  },
  {
    id: "INS-2409",
    lotNumber: "LOT-2026-08114",
    partNumber: "TNX-7788-B",
    partName: "Actuator Housing Cover",
    supplierId: "SUP-003",
    poNumber: "PO-88174",
    receivedDate: "2026-08-14",
    inspectedBy: "M. Delgado",
    sampleSize: 50,
    lotQuantity: 1200,
    passCount: 46,
    failCount: 4,
    aqlLevel: "1.5",
    disposition: "Return to Supplier",
    inspectorNotes:
      "Flash at parting line exceeds 0.15 mm limit on 4 samples. Exceeds AQL rejection number; lot returned.",
  },
  {
    id: "INS-2408",
    lotNumber: "LOT-2026-08110",
    partNumber: "TNX-3320-D",
    partName: "Bracket Stamping LH",
    supplierId: "SUP-004",
    poNumber: "PO-88152",
    receivedDate: "2026-08-12",
    inspectedBy: "R. Okafor",
    sampleSize: 50,
    lotQuantity: 2000,
    passCount: 43,
    failCount: 7,
    aqlLevel: "1.5",
    disposition: "Rejected",
    inspectorNotes:
      "Edge cracking on flange radius. NCR-2608 raised. Lot segregated in quarantine cage Q-3.",
  },
  {
    id: "INS-2407",
    lotNumber: "LOT-2026-08107",
    partNumber: "TNX-9910-E",
    partName: "Control Board Assembly Rev C",
    supplierId: "SUP-005",
    poNumber: "PO-88140",
    receivedDate: "2026-08-11",
    inspectedBy: "T. Nakamura",
    sampleSize: 20,
    lotQuantity: 250,
    passCount: 20,
    failCount: 0,
    aqlLevel: "0.65",
    disposition: "Accepted",
    inspectorNotes:
      "Functional test 100% pass. Solder joint inspection per IPC-A-610 Class 3.",
  },
  {
    id: "INS-2406",
    lotNumber: "LOT-2026-08103",
    partNumber: "TNX-5560-F",
    partName: "Shaft Blank 42CrMo4 QT",
    supplierId: "SUP-006",
    poNumber: "PO-88129",
    receivedDate: "2026-08-10",
    inspectedBy: "J. Whitfield",
    sampleSize: 8,
    lotQuantity: 600,
    passCount: 8,
    failCount: 0,
    aqlLevel: "1.0",
    disposition: "Accepted",
    inspectorNotes:
      "Hardness 288–302 HB within spec band. Certification traceable to heat lot H-4471.",
  },
  {
    id: "INS-2405",
    lotNumber: "LOT-2026-08099",
    partNumber: "TNX-1180-G",
    partName: "Harness Assembly 12-Way",
    supplierId: "SUP-007",
    poNumber: "PO-88115",
    receivedDate: "2026-08-08",
    inspectedBy: "M. Delgado",
    sampleSize: 20,
    lotQuantity: 500,
    passCount: 20,
    failCount: 0,
    aqlLevel: "1.0",
    disposition: "Accepted",
    inspectorNotes:
      "Continuity and hipot test complete. No crimp height deviations observed.",
  },
  {
    id: "INS-2404",
    lotNumber: "LOT-2026-08095",
    partNumber: "TNX-2044-H",
    partName: "Spindle Bearing Journal Pin",
    supplierId: "SUP-008",
    poNumber: "PO-88097",
    receivedDate: "2026-08-06",
    inspectedBy: "R. Okafor",
    sampleSize: 32,
    lotQuantity: 800,
    passCount: 27,
    failCount: 5,
    aqlLevel: "0.65",
    disposition: "Rejected",
    inspectorNotes:
      "Surface finish Ra 1.9 um vs. 0.8 um requirement. NCR-2605 raised; supplier notified same day.",
  },
  {
    id: "INS-2403",
    lotNumber: "LOT-2026-08091",
    partNumber: "TNX-6621-J",
    partName: "Compressor Cover Gasket",
    supplierId: "SUP-009",
    poNumber: "PO-88082",
    receivedDate: "2026-08-05",
    inspectedBy: "T. Nakamura",
    sampleSize: 50,
    lotQuantity: 3000,
    passCount: 48,
    failCount: 2,
    aqlLevel: "1.5",
    disposition: "Accepted",
    inspectorNotes:
      "Minor die marks outside sealing zone. Within AQL acceptance criteria.",
  },
  {
    id: "INS-2402",
    lotNumber: "LOT-2026-08087",
    partNumber: "TNX-8830-K",
    partName: "Anodized Trim Extrusion",
    supplierId: "SUP-010",
    poNumber: "PO-88071",
    receivedDate: "2026-08-04",
    inspectedBy: "J. Whitfield",
    sampleSize: 32,
    lotQuantity: 900,
    passCount: 29,
    failCount: 3,
    aqlLevel: "1.5",
    disposition: "Use As Is",
    inspectorNotes:
      "Coating thickness 9.2 um vs 10 um min on 3 samples. Deviation DEV-2614 approved by engineering.",
  },
  {
    id: "INS-2401",
    lotNumber: "LOT-2026-08082",
    partNumber: "TNX-3050-L",
    partName: "Valve Return Spring",
    supplierId: "SUP-011",
    poNumber: "PO-88058",
    receivedDate: "2026-08-03",
    inspectedBy: "M. Delgado",
    sampleSize: 32,
    lotQuantity: 10000,
    passCount: 32,
    failCount: 0,
    aqlLevel: "1.0",
    disposition: "Accepted",
    inspectorNotes:
      "Spring rate and free length verified. Load-deflection curve nominal.",
  },
  {
    id: "INS-2400",
    lotNumber: "LOT-2026-08078",
    partNumber: "TNX-4122-M",
    partName: "Diaphragm Seal NBR-70",
    supplierId: "SUP-012",
    poNumber: "PO-88044",
    receivedDate: "2026-08-01",
    inspectedBy: "R. Okafor",
    sampleSize: 50,
    lotQuantity: 4500,
    passCount: 47,
    failCount: 3,
    aqlLevel: "2.5",
    disposition: "Accepted",
    inspectorNotes:
      "Shore hardness 69–72A. Two units with minor gate vestige; functionally acceptable.",
  },
];

function eightD(doneCount: number) {
  const steps = [
    { step: "D1", label: "Team Formed" },
    { step: "D2", label: "Problem Described" },
    { step: "D3", label: "Containment" },
    { step: "D4", label: "Root Cause" },
    { step: "D5", label: "Corrective Actions" },
    { step: "D6", label: "Implemented" },
    { step: "D7", label: "Prevent Recurrence" },
    { step: "D8", label: "Team Recognition" },
  ];
  return steps.map((s, i) => ({ ...s, done: i < doneCount }));
}

export const ncrs: NonConformanceReport[] = [
  {
    id: "NCR-2608",
    supplierId: "SUP-004",
    partNumber: "TNX-3320-D",
    title: "Flange edge cracking on bracket stampings",
    defectDescription:
      "Incoming inspection found radial edge cracks along the flange bend radius on 7 of 50 sampled brackets (LOT-2026-08110). Cracks initiate at the trim edge and propagate into the form radius, consistent with excessive blanking burr and insufficient clearance.",
    priority: "Critical",
    status: "Investigating",
    raisedDate: "2026-08-12",
    raisedBy: "R. Okafor",
    containmentAction:
      "Lot of 2,000 pcs quarantined in cage Q-3. Line-side stock verified clear. Interim 100% visual inspection at goods-in until further notice.",
    rootCause: "",
    quantityAffected: 2000,
    costImpactUsd: 18500,
    eightDProgress: eightD(2),
  },
  {
    id: "NCR-2605",
    supplierId: "SUP-008",
    partNumber: "TNX-2044-H",
    title: "Journal pin surface finish out of specification",
    defectDescription:
      "Ground spindle pins measured Ra 1.9 um against drawing requirement of 0.8 um max. Five of 32 sampled parts failed profilometry (LOT-2026-08095). Risk of premature bearing wear in service.",
    priority: "Critical",
    status: "Containment Done",
    raisedDate: "2026-08-06",
    raisedBy: "R. Okafor",
    containmentAction:
      "Lot rejected and returned. All Redstone-machined pin lots from June onward recalled from FG stores and re-inspected; two additional suspect lots identified and quarantined.",
    rootCause: "",
    quantityAffected: 800,
    costImpactUsd: 42300,
    eightDProgress: eightD(3),
  },
  {
    id: "NCR-2601",
    supplierId: "SUP-013",
    partNumber: "TNX-6415-N",
    title: "Valve seat leakage above acceptance rate",
    defectDescription:
      "Customer returns traced to seat leakage exceeding 0.5 mL/min bubble test limit. Investigation linked to inconsistent lapping compound removal before assembly.",
    priority: "Major",
    status: "Root Cause Identified",
    raisedDate: "2026-07-21",
    raisedBy: "T. Nakamura",
    containmentAction:
      "All finished valves held; 100% bubble test re-screen completed on 1,400 units. 38 leakers scrapped.",
    rootCause:
      "Work instruction omitted final rinse after lapping. Compound residue caused intermittent seating during thermal cycling.",
    quantityAffected: 1400,
    costImpactUsd: 26800,
    eightDProgress: eightD(4),
  },
  {
    id: "NCR-2598",
    supplierId: "SUP-010",
    partNumber: "TNX-8830-K",
    title: "Anodic coating thickness below minimum",
    defectDescription:
      "Type II anodize measured 9.2 um average versus 10 um minimum on sampled trim extrusions. Corrosion resistance margin reduced for outdoor exposure variants.",
    priority: "Major",
    status: "Verified",
    raisedDate: "2026-07-08",
    raisedBy: "J. Whitfield",
    containmentAction:
      "Affected lot released under deviation DEV-2614 for interior-use assemblies only. Outdoor allocations redirected to alternate anodizer.",
    rootCause:
      "Rack density increased without re-validating current density; low current density produced thin coatings on rack centers.",
    quantityAffected: 900,
    costImpactUsd: 7600,
    eightDProgress: eightD(6),
  },
  {
    id: "NCR-2594",
    supplierId: "SUP-003",
    partNumber: "TNX-7788-B",
    title: "Molding flash at actuator cover parting line",
    defectDescription:
      "Recurring flash up to 0.3 mm at parting line across three consecutive lots. Flash interferes with cover seal engagement during customer assembly.",
    priority: "Major",
    status: "Closed",
    raisedDate: "2026-06-17",
    raisedBy: "M. Delgado",
    containmentAction:
      "Three lots sorted 100%; 210 pieces rejected and returned for credit.",
    rootCause:
      "Tooling clamp wear allowed mold breathing at shot pressure. Tool refurbished with new clamp rails and vent re-cut.",
    quantityAffected: 3600,
    costImpactUsd: 11200,
    eightDProgress: eightD(8),
  },
  {
    id: "NCR-2611",
    supplierId: "SUP-006",
    partNumber: "TNX-5560-F",
    title: "Missing material certification revision",
    defectDescription:
      "Mill certs supplied referenced superseded revision of AMS 2759/1 heat treat spec. Documentation only; product hardness verified compliant.",
    priority: "Minor",
    status: "Open",
    raisedDate: "2026-08-20",
    raisedBy: "J. Whitfield",
    containmentAction:
      "Certs requested from supplier. Product placed on document hold pending corrected certification.",
    rootCause: "",
    quantityAffected: 600,
    costImpactUsd: 0,
    eightDProgress: eightD(1),
  },
  {
    id: "NCR-2609",
    supplierId: "SUP-012",
    partNumber: "TNX-4122-M",
    title: "Gate vestige on diaphragm seals",
    defectDescription:
      "Cosmetic gate vestige noted on 2 of 50 sampled diaphragm seals. Vestige located outside functional seal area; no leak path identified.",
    priority: "Observation",
    status: "Investigating",
    raisedDate: "2026-08-15",
    raisedBy: "T. Nakamura",
    containmentAction:
      "None required; observation recorded for supplier process review at next visit.",
    rootCause: "",
    quantityAffected: 0,
    costImpactUsd: 0,
    eightDProgress: eightD(1),
  },
  {
    id: "NCR-2603",
    supplierId: "SUP-005",
    partNumber: "TNX-9910-E",
    title: "Reflow tombstone on control boards",
    defectDescription:
      "Two of 250 boards failed AOI with tombstoned 0402 resistors on power rail. Boards failed functional test and were repaired under IPC-A-610.",
    priority: "Minor",
    status: "Closed",
    raisedDate: "2026-06-30",
    raisedBy: "T. Nakamura",
    containmentAction:
      "Failed units repaired and re-tested. AOI escape review performed on prior two lots.",
    rootCause:
      "Uneven pad solder paste volume due to worn stencil apertures. Stencil replaced and aperture design updated.",
    quantityAffected: 250,
    costImpactUsd: 1800,
    eightDProgress: eightD(8),
  },
];

export const documents: VaultDocument[] = [
  {
    id: "DOC-101",
    name: "PPAP Level 3 Submission - TNX-3320-D Bracket.pdf",
    version: "Rev C",
    uploadedDate: "2026-08-14",
    uploadedBy: "Ironbridge Stampings",
    approvalStatus: "Pending Review",
    fileType: "pdf",
    sizeKb: 8420,
  },
  {
    id: "DOC-102",
    name: "Control Plan - Actuator Housing Cover.xlsx",
    version: "v4.2",
    uploadedDate: "2026-08-09",
    uploadedBy: "Cascade Polymer Solutions",
    approvalStatus: "Approved",
    fileType: "xlsx",
    sizeKb: 310,
  },
  {
    id: "DOC-103",
    name: "PFMEA - Spindle Journal Pin Machining.pdf",
    version: "v2.0",
    uploadedDate: "2026-08-05",
    uploadedBy: "Redstone Machining Works",
    approvalStatus: "Conditional",
    fileType: "pdf",
    sizeKb: 1290,
  },
  {
    id: "DOC-104",
    name: "IMDS Entry Confirmation - Trim Extrusion.pdf",
    version: "Rev B",
    uploadedDate: "2026-07-28",
    uploadedBy: "Keystone Extrusions",
    approvalStatus: "Approved",
    fileType: "pdf",
    sizeKb: 480,
  },
  {
    id: "DOC-105",
    name: "Calibration Certificates Bundle Q3.xlsx",
    version: "v1.1",
    uploadedDate: "2026-07-25",
    uploadedBy: "Summit Heat Treating Co.",
    approvalStatus: "Approved",
    fileType: "xlsx",
    sizeKb: 720,
  },
  {
    id: "DOC-106",
    name: "ISO 9001:2015 Certificate - Meridian.pdf",
    version: "2026 Issue",
    uploadedDate: "2026-07-19",
    uploadedBy: "Meridian Precision Castings",
    approvalStatus: "Approved",
    fileType: "pdf",
    sizeKb: 950,
  },
  {
    id: "DOC-107",
    name: "Deviation Request DEV-2614 - Anodize Thickness.docx",
    version: "v1.0",
    uploadedDate: "2026-08-04",
    uploadedBy: "Quality Engineering",
    approvalStatus: "Approved",
    fileType: "docx",
    sizeKb: 145,
  },
  {
    id: "DOC-108",
    name: "Annual Capacity Survey - Vantage EM.docx",
    version: "v3.0",
    uploadedDate: "2026-07-11",
    uploadedBy: "Vantage Electronics Mfg.",
    approvalStatus: "Pending Review",
    fileType: "docx",
    sizeKb: 260,
  },
];

export const audits: AuditEntry[] = [
  {
    id: "AUD-2631",
    type: "Process Audit",
    auditor: "R. Okafor",
    location: "Ironbridge Stampings — Toledo, OH",
    date: "2026-08-27",
    status: "Scheduled",
    supplierId: "SUP-004",
  },
  {
    id: "AUD-2632",
    type: "Product Audit",
    auditor: "M. Delgado",
    location: "Totalonics Goods-In Lab — Bay 4",
    date: "2026-08-29",
    status: "In Progress",
  },
  {
    id: "AUD-2633",
    type: "System Audit",
    auditor: "L. Brennan",
    location: "Redstone Machining Works — Erie, PA",
    date: "2026-09-03",
    status: "Scheduled",
    supplierId: "SUP-008",
  },
  {
    id: "AUD-2630",
    type: "Surveillance Audit",
    auditor: "BSI (external)",
    location: "Totalonics HQ — Building 1",
    date: "2026-09-15",
    status: "Scheduled",
  },
  {
    id: "AUD-2628",
    type: "System Audit",
    auditor: "J. Whitfield",
    location: "Cascade Polymer Solutions — Tacoma, WA",
    date: "2026-07-30",
    status: "Completed",
    supplierId: "SUP-003",
  },
  {
    id: "AUD-2626",
    type: "Process Audit",
    auditor: "R. Okafor",
    location: "Apex Surface Finishing — Dayton, OH",
    date: "2026-07-16",
    status: "Overdue",
    supplierId: "SUP-010",
  },
];

export const dashboardStats: DashboardStats = {
  totalSuppliers: suppliers.length,
  activeNcrs: ncrs.filter((n) => n.status !== "Closed").length,
  avgPassRate:
    Math.round(
      (inspections.reduce(
        (acc, i) => acc + (i.passCount / Math.max(i.sampleSize, 1)) * 100,
        0,
      ) /
        inspections.length) *
        10,
    ) / 10,
  overdueCorrectiveActions: 4,
};

export const lastAuditDate = "2025-09-12";
export const nextSurveillanceAudit = "2026-09-15";

export function getSupplier(supplierId: string): Supplier | undefined {
  return suppliers.find((s) => s.id === supplierId);
}
